# Generated by Django 5.0.6 on 2024-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
