# Generated by Django 5.0.6 on 2024-06-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_alter_skill_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="Level",
            field=models.CharField(default="Expert", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(default="Household", max_length=20),
            preserve_default=False,
        ),
    ]
