# Generated by Django 5.0.6 on 2024-07-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
