# Generated by Django 5.0.6 on 2024-07-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_message_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="skill_deal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_for_deal",
                to="skills.skilldeal",
            ),
            preserve_default=False,
        ),
    ]
